// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs4UTqlHS3HB1WKG_vmPPkopNFdnM1lMQ',
    appId: '1:614429174674:android:7a9d96eddd5e7b39832f4b',
    messagingSenderId: '614429174674',
    projectId: 'final-project-8fbf0',
    storageBucket: 'final-project-8fbf0.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPzKFO6KeYOns3f4hN5vkCqPZIt6QZP9Y',
    appId: '1:614429174674:web:defe7bfe008dfdbd832f4b',
    messagingSenderId: '614429174674',
    projectId: 'final-project-8fbf0',
    authDomain: 'final-project-8fbf0.firebaseapp.com',
    storageBucket: 'final-project-8fbf0.appspot.com',
    measurementId: 'G-S4G6YD9T43',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPF1VKVjhPmJHsbGWnBJnn5DfzIe3QfOU',
    appId: '1:614429174674:ios:6e1afd9ad6915447832f4b',
    messagingSenderId: '614429174674',
    projectId: 'final-project-8fbf0',
    storageBucket: 'final-project-8fbf0.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPF1VKVjhPmJHsbGWnBJnn5DfzIe3QfOU',
    appId: '1:614429174674:ios:6e1afd9ad6915447832f4b',
    messagingSenderId: '614429174674',
    projectId: 'final-project-8fbf0',
    storageBucket: 'final-project-8fbf0.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPzKFO6KeYOns3f4hN5vkCqPZIt6QZP9Y',
    appId: '1:614429174674:web:d6f98a01bd014bdd832f4b',
    messagingSenderId: '614429174674',
    projectId: 'final-project-8fbf0',
    authDomain: 'final-project-8fbf0.firebaseapp.com',
    storageBucket: 'final-project-8fbf0.appspot.com',
    measurementId: 'G-GNZMLLTDY6',
  );

}